# Generated by Django 5.2.3 on 2025-07-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_category_listing_active_user_watchlist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="picture",
        ),
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
