# Generated by Django 5.2.3 on 2025-07-02 19:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_remove_category_picture_remove_listing_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="starting_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.01"), max_digits=7
            ),
        ),
    ]
