# Generated by Django 5.2.3 on 2025-07-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_rename_name_listing_title_listing_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
