# Generated by Django 5.2.3 on 2025-07-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_alter_listing_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="placed",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
